### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-html-multiple-pages-T_njfg#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://mi-449-ss17-740-html-multiple-pages-t_njfg-lordcrekit.surge.sh/) and meets the following criteria:

- [x] None of the routes on the website end with `.html`
- [x] A homepage exists, where the purpose of the site is explained
- [x] A "list page" exists that lists your top 3 favorite of this thing (e.g. `/pokemon`) -- each list item should link to the corresponding page for that favorite, detailed below
- [x] For each of your favorites, a page exists to display more information about it (e.g. `/pokemon/bulbasaur`)
- [x] Every page includes links to the homepage and list page (although pages do not have to link to themselves)

**Comment by KatieMFritz** [comment]
Oooh Bootstrap - fancy! Love that intro, too. 😆 And you even included a favicon (:hankey: though it may be). 

Great job with the `index.html`s, the content of the site, and using root-relative links. 👍 

This is really close, but there are a couple criteria you haven't quite met yet. Fortunately, the fixes are pretty easy.

**> - A "list page" exists that lists your top 3 favorite of this thing (e.g. /pokemon)...**

You have this, and looks great, but the URL (/list) is not descriptive. It's important (for SEO and usability) for every part of a URL to provide information about the page. In this case, I would change `list` to `games` or `the-games` (to reflect the `h1` on that page). Does that make sense to you?

* * *

**>  - For each of your favorites, a page exists to display more information about it (e.g. /pokemon/bulbasaur)**

You've got the links, but the individual games pages are all at the same level of the site as the list page. Take another look at [the nested routes page of the lesson](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-multiple-pages/4) and see if you can get your URLs to be `mysite.com/games/sonic-06` instead of `mysite.com/sonic-06` (where `mysite.com` is of course your gh-pages URL). 

* * * 
**Bonus improvement: descriptive link text**

You might recall that I'm big on UX (user experience). 🤓 On your individual game pages, you use the text "Back." to link back to the list of games. 

This is not terrible, but it could be even more user friendly if it said where back _was_, for example "Back to the games", "All games", "The Games," "list of games", or some other variation of that. 

I'll still ship this without that change, but make it if you have time, and consider it for future projects! 😄 

* * *
After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by lordcrekit** [comment]
Done, done, and done.

**Comment by KatieMFritz** [comment]
Awesome! 🎮 

:shipit:
